seismo-learn/software

- .github/workflows/build.yml
- Remove unneeded codes
- Only deploy the website for the main branch
- Only keep the last commit to make the gh-pages branch small
> Improve workflow

- README.md
> Add instrucitons to build the site

- source/_templates/layout.html
- source/conf.py
> Add external links to sidebar

- source/conf.py
> Show last update date in the footer

- source/conf.py
Change "源代码" to "网站源码" so that all links have 4 Chinese characters.
> Update link name

- source/conf.py
> Fix the site titles

- source/conf.py
Update the `conf.py` so that when we want to create new websites,
we only need to update the project information.
> Update conf.py to make it simple to creata new websites

- source/taup/index.rst
- source/taup/introduction.rst
- Add the link to the official documentation
- Add one more software author as indicated in the official
documentation
- Add one reference
> taup: Add more metadata and references

- source/taup/index.rst
- source/template/index.rst
> Fix authors to contributors

- source/index.rst
> Add a link to HinetPy

- source/index.rst
> Improve the sidebar

- .github/labeler.yml
- source/hinetpy/index.rst
- source/index.rst
> HinetPy: Add metadata page for HinetPy

- .github/labeler.yml
- source/index.rst
- source/sac/index.rst
> SAC: Add metadata page for SAC

- source/gmt/index.rst
> GMT: Fix metadata

- source/gmt/index.rst
- source/hinetpy/index.rst
- source/index.rst
> Tiny fixes and update index

- source/obspy/install.rst
- source/obspy/introduction.rst
- Fix English () to Chinese （）
- Use `--name` instead of `-n`. The former one is easier to understand
- Add more links
> ObsPy: Tiny fixes

- .github/workflows/build.yml
- README.md
Change workflow name from "Build Website" to "CI" and also update the badge link.
> Change CI workflow name

- source/anaconda/index.rst
In case we need to update the distribution, it is better to first of all 
update the package manager and then update the meta-package
See https://mauridb.medium.com/how-to-check-your-anaconda-version-c092400c9978
> Change the order of updating conda and anaconda

- source/_static/custom.css
- source/conf.py
Increase content width to 1000px.
Before:
After:
> Increase the page width

- source/anaconda/index.rst
> anaconda: Fix install instructions

- source/obspy/install.rst
Otherwise we may have mixed packages from both main and conda-forge.
> Fix obspy installation

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .github/labeler.yml
- .github/workflows/test.yml
- .github/workflows/tests.yml
- README.md
- tests/test-obspy.sh
Address #135.
This PR adds a workflow which runs scripts weekly. 
Currently, only obspy is tested. All tests are in the `tests` directory.
> Workflow to test installations weekly

- .github/workflows/tests.yml
- tests/test-distaz.sh
- tests/test-sod.sh
- tests/test-taup.sh
This PR adds some tests for SOD, TauP and distaz.
Address #135.
Environment:
Software to test:
Software without tests:
> Add more tests in weekly CI jobs

- source/cps/install.rst
https://github.com/seismo-learn/seismology101/issues/90
> CPS: Add instructions for X11

- README.md
Clicking the badges will direct us to the GitHub Actions page.
> Let the badges link to the actions page

- source/conf.py
> Add whitespace between number and Chinese char

- requirements.txt
- source/conf.py
See https://sphinx-copybutton.readthedocs.io/en/latest/
Related to https://github.com/seismo-learn/seismology101/issues/144
> Add the sphinx-copybutton extension

- .github/workflows/tests.yml
> Fix broken tests

- .github/workflows/deploy.yml
- .github/workflows/preview-pr.yml
> Bump styfle/cancel-workflow-action version to 0.8.0

- .github/workflows/check-links.yml
> Exclude some invalid links in check-links.yml

- .github/workflows/check-links.yml
> Fix a typo

- requirements.txt
> Pin docutils to 0.16

- .github/workflows/deploy.yml
- .github/workflows/preview-pr.yml
- .github/workflows/tests.yml
> Bump styfle/cancel-workflow to v0.9.0

- .github/dependabot.yml
> Add dependabot to automatically update action versions

- source/taup/install.rst
> Update TauP install instructions

- .github/workflows/check-links.yml
> Update check-links workflow

- source/taup/taup_setsac.rst
> Update taup-setsac tutorial

- source/taup/introduction.rst
We don't need the indentation only for taup GUI
> Tiny improve taup introduction

- source/taup/index.rst
- source/taup/introduction.rst
- source/taup/taup_table.rst
> Add taup-table tutorial

- source/locales/zh_CN/LC_MESSAGES/sphinx.po
> Update Chinese translations of Sphinx strings

- .github/workflows/compress-images.yml
> Add a workflow to compress static images in PRs

- requirements.txt
- source/anaconda/index.rst
- source/conf.py
- source/cps/install.rst
- source/index.rst
- source/java/index.rst
- source/snippets/install-notes.rst_
> Replace sphinx-panels with sphinx-design

- source/anaconda/index.rst
Closes https://github.com/seismo-learn/seismology101/issues/439
> Recommend mamba instead of conda

- README.md
> Add the JupyterBook badge

- source/index.md
> Improve the landing page

- source/cps/index.md
- source/fk/index.md
- source/gcap3d/index.md
- source/obspy/index.md
- source/sod/index.md
- source/taup/index.md
- source/template/index.md
Make sure that metadata for all software have the same order.
> Use consistent order for matadata

- source/index.md
Data downloading and processing are more important than other software, so they should be the first
> Reorder of the software categories based on importance

- .github/workflows/deploy.yml
Fixes #
**PRs for adding a new software**
**PRs for adding a new tutorial**
the tutorials are listed in the metadata page
> Migrate provision-with-micromamba to setup-micromamba

- source/java/index.md
Fixes #
**PRs for adding a new software**
**PRs for adding a new tutorial**
the tutorials are listed in the metadata page
> Install the latest openjdk on Fedora
